extends: airbnb-base
env:
  node: true
  mocha: true
rules:
  no-param-reassign: "off"
  no-console: "off"
overrides:
  - files:
      - "**/*-example.js"
      - api/v1/db/awsS3/aws-operations.js
    rules:
      import/no-unresolved: "off"
